packages:
  # Base plugins
  - 'plugins/*'

  # Extension plugins
  - 'extensions/*'

  # Shared libraries
  - 'packages/*'

  # Development tooling
  - 'tooling/*'

  # Documentation website
  - 'website'
