import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Auto-generate sidebars from the docs directory structure
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
}

// eslint-disable-next-line import/no-default-export
export default sidebars
